BATCH_SIZE: int = 8
SEED: int = 123
LABEL_MODE: str = 'int'
IMAGE_SIZE: tuple = (224, 224)
INTERPOLATION: str = "bilinear"
COLOR: str = 'rgb'
LABELS: str = "inferred"
VALIDATION_SPLIT: float = 0.3
DATA_PATH: str = "/mnt/d/Tojo Sir - Project/"
